### PR TITLE
Fix ... all of traversal

### LINKED ISSUE #22: Ring is incorrect when not saturated
If the ring isn't "saturated" - i.e. has not been filled to capacity - then the `Inspect` method (and thus the `Scan*` helpers) will incorrectly return a range that includes one value past the end of the filled ring. See the following playground link for an example:

https://play.golang.org/p/v6H-fwd26SG

### PR DESCRIPTION
**Pull request by antifuchs**
# What does this change do?

This PR updates LIFO and FIFO traversal with `Scanner`s, to, uh, ...

* be the right way around
* not have off-by-one errors in non-wrapping ring traversals
* be understandable

Fixes #22.

# Tests for the change

This is funny: I had tests for all of this, but the tests were wrong (exercising LIFO/FIFO traversal in the wrong order), or they didn't cover the case that triggered the bug.

I fixed the tests, added ones for cases that were missing.

# Checklist for code changes

- [x] Is this a code change? If so:
  - [x] Made a test for the change
- [x] Check project test coverage remains at 100%
- [x] Added an entry to [CHANGELOG.md](../../blob/master/CHANGELOG.md)

### CODE REVIEW

File: ring.go [hunk 1]
```diff
@@ -39,7 +39,8 @@ type ringBackend interface {
 	// start returns the index of first element that can be read.
 	start() uint
 
-	// end returns the index of the last element that can be read.
+	// end returns the index after the last element that can be
+	// read. It is compatible with go [:] slice expressions.
```
Comment (antifuchs) [inline ring.go:43]: I think this comment is what caused alllllll my confusion, leading up to the off-by-one. Hopefully fixing the internal docs here will prevent more of that (:
